call plug#begin('~/.vim/plugged')
Plug 'scrooloose/nerdtree'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'tpope/vim-commentary'
Plug 'leafgarland/typescript-vim'
Plug 'ntpeters/vim-better-whitespace'
Plug 'mileszs/ack.vim'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-rhubarb'
Plug 'morhetz/gruvbox'
Plug 'lifepillar/vim-solarized8'
Plug 'vim-ruby/vim-ruby'
Plug 'w0rp/ale'
Plug 'tpope/vim-surround'
Plug 'markabe/bufexplorer'
Plug 'sheerun/vim-polyglot'
Plug 'lambdalisue/gina.vim'
Plug 'tpope/vim-cucumber'
call plug#end()

syntax on

set termguicolors
colo solarized8
set background=dark

set spelllang=en_us
" set spell
set et sw=2 ts=2
autocmd Filetype php setlocal sw=4 ts=4
set autoindent
set wildmenu wildmode=list:longest,full
set ignorecase smartcase
set hlsearch
set incsearch
set hidden

let g:ctrlp_map = ''
let g:ctrlp_user_command = 'fd -t f -H -E .git'
let g:ctrlp_mruf_relative = 1
let g:strip_whitespace_on_save = 1
let g:strip_whitespace_confirm = 0
let g:ackprg = 'rg --vimgrep --smart-case'
" let g:ale_linters = {
"       \ 'javascript': ['jshint'],
"       \ }

nm <silent> <c-p> :Files<CR>
nm <silent> <c-l> :nohls<CR>
nm <silent> <leader>B :Buffers<CR>
nm <silent> <leader>f :NERDTreeFind<CR>

au BufReadPost .rspec-distrib set filetype=ruby
au BufReadPost Jenkinsfile set filetype=groovy
